name: PyPI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9'

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
