name: Tests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install package with dev extra
        run: |
          pip install .
          pip install pytest pytest-cov pytest-mock
      - name: Run tests
        run: python -m pytest

